### ISSUE TITLE
AssertionError when running random_forest script on hmeq data

### ISSUE THREAD

**Issue by hgupta18** [johannes-kk/cs205_final_project#114]
I got `Assertion failed: (i<this->size()), function value, file ../speedup/../src-openmp/datasets.cpp, line 46.` when I ran the `speedup/rf_serial_hmeq.cpp` or `speedup/rf_openmp_hmeq.cpp` scripts.

**Comment by johannes-kk** [comment]
Does the dataset have any missing values? If the dataset is successfully imported into a DataFrame then missingness likely isn’t the cause.

**Comment by johannes-kk** [comment]
It seems to be a data issue. It's not tied to number of rows, as simply copying `Sonar` several times to make about 2,000 rows still works with any number of trees.

**Comment by johannes-kk** [comment]
Nevermind, seems to be an issue with `DecisionTree.findBestSplit()`. Running the Sonar dataset artificially made into 2,000 rows (by copying it several times) with 5,000 trees causes `/speedup/rf_openmp.cpp` to fail after about 40min with:
```
Assertion failed: (this->isFitted()), function predict, file ../speedup/../src-openmp/decision_tree.cpp, line 396.
Accuracy train: Abort trap: 6
```

It is, in other words, a problem caused by the combination of `ntrees` and dataset `length` being "too big" in one way or another.
